SELECT * FROM PRODUCTS;
--This is the top 3 most expensive products in each category using ROW_NUMBER(),RANK(),DENSE_RANK()
WITH PRODUCT_RANKS AS(
	SELECT PRODUCTID,PRODUCTNAME,CATEGORY,PRICE, 
	ROW_NUMBER() OVER( PARTITION BY CATEGORY ORDER BY PRICE DESC) AS ROW_NUMBER_RANK,
	RANK() OVER( PARTITION BY CATEGORY ORDER BY PRICE DESC) AS _RANK,
	DENSE_RANK() OVER( PARTITION BY CATEGORY ORDER BY PRICE DESC) AS _DENSE_RANK
	FROM PRODUCTS
)
SELECT PRODUCTID, PRODUCTNAME, CATEGORY, PRICE, ROW_NUMBER_RANK,_RANK,_DENSE_RANK
FROM PRODUCT_RANKS
WHERE ROW_NUMBER_RANK<=3 or _RANK=1 OR _DENSE_RANK=1 ORDER BY PRICE DESC;

--This is the top 3 most expensive products...I used where clause to restrict other products other than top 3, and other two where clauses are used to disply elements in same price..